model_list:
  - model_name: claude-opus-4-6
    litellm_params:
      model: anthropic/MiniMax-M2.5
      api_base: https://api.minimaxi.com/anthropic
      api_key: os.environ/MINIMAX_API_KEY

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/MiniMax-M2.5
      api_base: https://api.minimaxi.com/anthropic
      api_key: os.environ/MINIMAX_API_KEY

  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/MiniMax-M2.5
      api_base: https://api.minimaxi.com/anthropic
      api_key: os.environ/MINIMAX_API_KEY

  - model_name: claude-opus-4-6
    litellm_params:
      model: anthropic/glm-4.7
      api_base: https://open.bigmodel.cn/api/anthropic
      api_key: os.environ/GLM_API_KEY

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/glm-4.7
      api_base: https://open.bigmodel.cn/api/anthropic
      api_key: os.environ/GLM_API_KEY

  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/glm-4.7
      api_base: https://open.bigmodel.cn/api/anthropic
      api_key: os.environ/GLM_API_KEY

  - model_name: embedding-3
    litellm_params:
      model: openai/embedding-3
      api_base: https://open.bigmodel.cn/api/paas/v4/
      api_key: os.environ/GLM_API_KEY
    model_info:
      mode: embedding

search_tools:
  - search_tool_name: tavily-search
    litellm_params:
      search_provider: tavily
      api_key: os.environ/TAVILY_API_KEY

mcp_servers:
  deepwiki:
    url: https://mcp.deepwiki.com/mcp
    transport: http
    allow_all_keys: true
    available_on_public_internet: true

  tavily:
    url: https://mcp.tavily.com/mcp/
    transport: http
    auth_type: bearer_token
    authentication_token: os.environ/TAVILY_API_KEY
    allow_all_keys: true
    available_on_public_internet: true

  n8n:
    url: http://n8n-mcp:3000/mcp
    transport: http
    auth_type: bearer_token
    authentication_token: os.environ/N8N_API_KEY
    allow_all_keys: true

  context7:
    url: https://mcp.context7.com/mcp
    transport: http
    auth_type: bearer_token
    authentication_token: os.environ/CONTEXT7_API_KEY
    allow_all_keys: true
    available_on_public_internet: true


litellm_settings:
  drop_params: True
  cache: True
  cache_params:
    type: redis
    host: redis
    port: 6379
    namespace: "litellm.caching.caching"
router_settings:
  routing_strategy: least-busy
  model_group_alias: {"claude-haiku-4-5-20251001": "claude-haiku-4-5"}
  redis_host: redis
  redis_port: 6379

general_settings:
  database_url: postgresql://postgres:postgres@postgres:5432/litellm
  master_key: sk-laGwcFtn4L2LAvC7Yav5Y17xZ7jTQ6J9vI034ICrqxo
  store_prompts_in_spend_logs: true
