services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  nextcloud:
    image: nextcloud:27.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html:z
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=homebox.lan
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  cron:
    image: nextcloud:27.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html:z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    entrypoint: /cron.sh

volumes:
  nextcloud_data:
  postgres_data:
  redis_data:
