x-common:
  &common
  image: apache/superset:4.0.2
  user: "root"
  env_file: superset.env
  restart: unless-stopped
  volumes:
    - superset-data:/app/superset_home
    - ./superset_config.py:/app/docker/pythonpath_dev/superset_config.py
  extra_hosts:
    - "host.docker.internal:172.17.0.1"  

volumes:
  superset-data:
services:
  webserver:
    <<: *common
    ports:
      - 8020:8088

  worker:
    <<: *common
    command: celery --app=superset.tasks.celery_app:app worker -O fair -l INFO
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
  init:
    <<: *common
    restart: no
    command: >
      bash -c "superset db upgrade && superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && superset init"
