version: '3.8'
volumes:
  db-data:
services:
  frontend:
    image: ghcr.io/modsetter/surfsense_ui:latest
    ports:
      - 8102:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://174.15.0.58:8101
      - NEXT_PUBLIC_FASTAPI_BACKEND_URL=http://174.15.0.58:8101
      - NEXT_PUBLIC_FASTAPI_BACKEND_AUTH_TYPE=LOCAL
      - NEXT_PUBLIC_ETL_SERVICE=DOCLING
  
  backend:
    image: ghcr.io/modsetter/surfsense_backend:latest
    ports:
      - 8101:8000
    environment:
      - NEXT_FRONTEND_URL=http://174.15.0.58:8102
      - BACKEND_PORT=8101
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-surfsense}
      - PYTHONPATH=/app
      - UVICORN_LOOP=asyncio
      - UNSTRUCTURED_HAS_PATCHED_LOOP=1
      - LANGCHAIN_TRACING_V2=false
      - LANGSMITH_TRACING=false
      - EMBEDDING_MODEL=mixedbread-ai/mxbai-embed-large-v1
      - RERANKERS_MODEL_NAME=mixedbread-ai/mxbai-rerank-large-v1
      - RERANKERS_MODEL_TYPE=cross-encoder
      - ETL_SERVICE=DOCLING
      - FIRECRAWL_API_KEY=fc-a8dfd43eede94b778d1fe539f784353a
      - HF_ENDPOINT=https://hf-mirror.com
      - SECRET_KEY=SECRET
  db:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surfsense
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
