volumes:
  conf:
  cert:
services:
  nginx:
    image: nginx:1.25.3-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d:ro
      - cert:/etc/nginx/cert:ro
