version: '3.8'

services:
  one-api:
    image: justsong/one-api
    container_name: one-api
    restart: unless-stopped
    ports:
      - "8002:3000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - data:/data

volumes:
  data:
