volumes:
  data:
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    command: --transaction-isolation=READ-COMMITTED --skip-log-bin --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=1G
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
