version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass redis_password
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  data:
